/**
 * File: worker-configuration.d.ts
 * Author: Dann Bleeker Pedersen
 * Created: 2026-06-12
 * Last Updated: 2026-06-12
 * Version: 1.0.0
 * Description: TypeScript types for the Worker's runtime bindings (env).
 *              Normally generated by `wrangler types` from wrangler.jsonc,
 *              hand-written here because we know exactly what bindings exist
 *              and avoid the 230kb auto-generated typedump.
 *
 *              Cloudflare's `env` (from `cloudflare:workers`) is typed as
 *              `Cloudflare.Env` — we use declaration merging to add our
 *              specific bindings to that interface. The top-level `Env`
 *              alias preserves the older `Env` syntax used by parts of the
 *              template (Hono bindings, McpAgent generic).
 *
 *              If you add a new binding to wrangler.jsonc, add a matching
 *              field here.
 *
 * Change log:
 *   1.0.0 (2026-06-12) — Initial.
 */

declare namespace Cloudflare {
	interface Env {
		// Durable Object holding MCP session state.
		MCP_OBJECT: DurableObjectNamespace;

		// KV namespace used by the OAuth provider for client state.
		OAUTH_KV: KVNamespace;

		// GitHub OAuth app (set via `wrangler secret put`).
		GITHUB_CLIENT_ID: string;
		GITHUB_CLIENT_SECRET: string;

		// Random secret used to encrypt the consent cookies.
		COOKIE_ENCRYPTION_KEY: string;

		// Trello credentials — never leave the Worker.
		TRELLO_KEY: string;
		TRELLO_TOKEN: string;
	}
}

// Top-level alias so existing `Env` references continue to work.
type Env = Cloudflare.Env;
